export const names = {
    firsts: [
        "Lars",
        "Fjörd",
        "Kröns",
        "Yasmin",
        "Dirk",
        "Bronson",
        "Kurt",
        "Klaus",
        "Hans",
        "Earl",
        "Ivanna",
        "Ol' Man",
        "Rusty",
        "Jerome",
        "Pierre",
        "Harrison",
        "Red",
        "Buster",
        "Ingrid",
        "Julius",
        "Sherman",
        "Junior",
        "Yuri",
        "John",
        "Ryder",
        "Gary",
        "Ari",
        "Pekka",
        "Eliza",
        "Lisa",
        "Sally",
        "Jasmine",
        "Rita",
        "Marjorie",
        "Melissa",
        "Terrence",
        "Ulrich Von",
        "Chief",
        "Helga Von",
        "Dusty",
        "Krusty",
        "Count",
        "Countess",
        "Matt",
        "Ben",
        "Jon",
        "Josh",
        "Misty",
        "Master",
        "Dr.",
        "Grandma",
        "Grandpa",
        "DJ",
        "Kitty",
        "Armando",
        "Santa",
        "Mother",
        "Buster",
        "Indiana",
        "Mama",
        "Papa",
        "Madame",
        "Monsieur",
        "Shawanna",
        "Cleopatra",
        "Ol'",
        "Constable",
        "Napoleon",
        "Mayor",
        "Detective",
        "Officer",
        "Trooper",
        "Lord",
        "Moby",
        "Ruth",
        "Scooter",
        "Kris",
        "Kathy",
        "Gerri",
        "Ron",
        "Ronald",
        "Dean",
        "Quincy",
        "Aslan",
    ],

    lasts: [
        "Jonesberg",
        "Ramsford",
        "Kirkson",
        "Von Buffington",
        "Craghammer",
        "McFly",
        "Schultz",
        "McAvery",
        "Jenkums",
        "Porter",
        "Winklecross",
        "Dillings",
        "Van Winkle",
        "Sparks",
        "Burns",
        "Drury",
        "Kirk",
        "Giovanni",
        "Sanderson",
        "Portenson",
        "Smith",
        "Jenkins",
        "Libbard",
        "Mantoya",
        "Pritchard",
        "Hansfield",
        "McDonald",
        "Rockford",
        "Higgs",
        "Jones",
        "Jackson",
        "Jefferson",
        "Kennedy",
        "Franklin",
        "Potter",
        "Hunt",
        "Pierce",
        "Thornsburg",
        "Trumbull",
        "Bellamew",
        "Bernstein",
        "Yates",
        "Hadley",
        "Wright",
        "Michaels",
        "Norrin",
        "Norris",
        "Verplank",
        "Vanderfleet",
        "Zynara",
        "Vance",
        "Xavier",
        "Poole",
    ],

    suffixes: [
        "Esq.",
        "M.D.",
        "O.D.",
        "DDS",
        "PhD",
        "PMP",
        "Sr.",
        "Jr.",
        "II",
        "III",
        "IV"
    ],

    catFirsts: [
        "Scratchy",
        "Puffy",
        "Lydia",
        "Creampuff",
        "Sargeant",
        "Corporal",
        "Admiral",
        "Major",
        "Captain",
        "Fluffy",
        "Fuzzy",
        "Poofy",
        "Squeeky",
        "Hairball",
        "Fiddius",
        "Duke",
        "Archibald",
        "Polly",
        "Licky",
        "Whiskers",
        "Notorious",
        "Paws",
        "Sabretooth",
        "Gerard",
        "Heathcliff",
        "Garfield",
        "Fish Breath",
        "Scruffy",
        "Sassy",
        "Muncey",
        "Jellybeans",
        "DJ",
        "Lil",
        "Cat",
        "Sniffles",
        "Madam",
        "Veronicat",
        "Nacho",
        "Tabby",
        "Itchy",
        "Tigger",
        "Flea"
    ],

    catLasts: [
        "Snuggles",
        "McPreen",
        "Von Crunch",
        "Sparkles",
        "At Arms",
        "Lixalot",
        "Purrmeister",
        "Furbottom",
        "McFuzz",
        "the cat",
        "C-A-T",
        "The Fierce",
        "The Lazy",
        "Everkitten",
        "The Spiteful",
        "The Hidden",
        "Litterpaws",
        "Tailwind",
        "Tailspin",
        "The Admiral",
        "Biscuits",
        "The Captain",
        "Von Lickenstein",
        "Clawsby",
        "Furr",
        "Flufferton",
        "Shakespurr"
    ]
}
